COLUMN_MAPPING = {
    "Row ID": "RowID",
    "Order ID": "OrderID",
    "Order Date": "OrderDate",
    "Ship Date": "ShipDate",
    "Ship Mode": "ShipMode",
    "Customer ID": "CustomerID",
    "Customer Name": "CustomerName",
    "Segment": "Segment",
    "Country/Region": "Country",
    "City": "City",
    "State": "State",
    "Postal Code": "PostalCode",
    "Region": "Region",
    "Product ID": "ProductID",
    "Category": "Category",
    "Sub-Category": "SubCategory",
    "Product Name": "ProductName",
    "Sales": "Sales",
    "Quantity": "Quantity",
    "Discount": "Discount",
    "Profit": "Profit",
    "Order Year": "OrderYear",
    "Order Month": "OrderMonth",
    "Order Month Name": "OrderMonthName",
    "Order Quarter": "OrderQuarter",
    "Order Day": "OrderDay",
    "Order Weekday": "OrderWeekday",
    "Shipping Days": "ShippingDays",
    "Profit Margin": "ProfitMargin",
    "Has Discount": "HasDiscount",
    "High Profit": "HighProfit",
    "Order Size": "OrderSize"
}